insert into wines (winery_id, name, style) values (11,'2017 Pinot Grigio','Dry White');
insert into wines (winery_id, name, style) values (11,'Festivus','Dry Red');
insert into wines (winery_id, name, style) values (11,'Winter Wite','Sweet White');
insert into wines (winery_id, name, style) values (11,'Great Lakes Red','Sweet Red');
insert into wines (winery_id, name, style) values (11,'Cherry','Fruit Wine');
insert into wines (winery_id, name, style) values (11,'Raspberry Dessert Wine','Dessert Wine');
insert into wines (winery_id, name, style) values (11,'2018 Chardonnay','Dry White');
insert into wines (winery_id, name, style) values (11,'Sleeping Bear Red','Dry Red');
insert into wines (winery_id, name, style) values (11,'2020 Brut','Sparkling');
insert into wines (winery_id, name, style) values (11,'Winter White Bubbly','Sparkling');
insert into wines (winery_id, name, style) values (11,'2018 Vintage Port','Dessert Wine');

insert into wine_rating (wine_id, user, date, rating) values (82,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (83,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (84,'lordgasmic','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (85,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (86,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (76,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (77,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (78,'lordgasmic','11/6/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (79,'lordgasmic','11/6/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (80,'lordgasmic','11/6/21','check');
insert into wine_rating (wine_id, user, date, rating) values (81,'lordgasmic','11/6/21','');

insert into wines (winery_id, name, style) values (16,'2017 Riesling','Hard Cider');
insert into wines (winery_id, name, style) values (16,'Old World','Hard Cider');
insert into wines (winery_id, name, style) values (16,'Cherry','Hard Cider');
insert into wines (winery_id, name, style) values (16,'Sangria','Hard Cider');
insert into wines (winery_id, name, style) values (16,'2020 Honeycrisp Ice Cider','Hard Cider');
insert into wines (winery_id, name, style) values (15,'Horseradish Vodka','Spirit');
insert into wines (winery_id, name, style) values (15,'Jack Pine Gin','Spirit');
insert into wines (winery_id, name, style) values (15,'Bernies Brandy','Spirit');
insert into wines (winery_id, name, style) values (15,'Deer Camp Straight Bourbon Whiskey','Spirit');
insert into wines (winery_id, name, style) values (15,'Deer Camp Vodka','Spirit');
insert into wines (winery_id, name, style) values (15,'Manitou Passage Rum','Spirit');
insert into wines (winery_id, name, style) values (15,'Michigan Dogman Moonshine','Spirit');

insert into wine_rating (wine_id, user, date, rating) values (96,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (97,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (94,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (95,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (98,'lordgasmic','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (92,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (93,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (94,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (95,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (87,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (88,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (89,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (90,'lordgasmic','11/6/21','check');
insert into wine_rating (wine_id, user, date, rating) values (91,'lordgasmic','11/6/21','');

insert into wines (winery_id, name, style) values (9,'2019 Dry Riesling','White');
insert into wines (winery_id, name, style) values (9,'2019 Unwooded Chardonnay','White');
insert into wines (winery_id, name, style) values (9,'2017 Pinot Gris','White');
insert into wines (winery_id, name, style) values (9,'2019 Skin Ferment Pinot Gris','Rose');
insert into wines (winery_id, name, style) values (9,'Cherry Dessert','Dessert Wine');
insert into wines (winery_id, name, style) values (10,'2019 Soiree','Sparkling');
insert into wines (winery_id, name, style) values (10,'2019 Rose de Pinot Noir','Rose');
insert into wines (winery_id, name, style) values (10,'2018 Lee La Tage','Red Wine');
insert into wines (winery_id, name, style) values (10,'2019 Ridge Red','Red Wine');

insert into wine_rating (wine_id, user, date, rating) values (104,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (105,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (106,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (107,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (99,'lordgasmic','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (100,'lordgasmic','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (101,'lordgasmic','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (102,'lordgasmic','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (103,'lordgasmic','9/5/21','check');
