insert into wine_rating (wine_id, user, date, rating) values (63,'lordgasmic','11/24/21','check plus');
insert into wine_rating (wine_id, user, date, rating) values (64,'lordgasmic','11/24/21','check plus plus');
insert into wine_rating (wine_id, user, date, rating) values (71,'lordgasmic','11/24/21','check minus');
insert into wine_rating (wine_id, user, date, rating) values (66,'lordgasmic','11/24/21','check');
insert into wine_rating (wine_id, user, date, rating) values (68,'lordgasmic','11/24/21','check');
insert into wine_rating (wine_id, user, date, rating) values (67,'lordgasmic','11/24/21','check');
insert into wine_rating (wine_id, user, date, rating) values (55,'lordgasmic','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (56,'lordgasmic','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (57,'lordgasmic','9/12/21','check');
insert into wine_rating (wine_id, user, date, rating) values (58,'lordgasmic','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (59,'lordgasmic','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (60,'lordgasmic','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (61,'lordgasmic','9/12/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (62,'lordgasmic','9/12/21','check');
insert into wine_rating (wine_id, user, date, rating) values (49,'lordgasmic','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (50,'lordgasmic','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (71,'lordgasmic','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (52,'lordgasmic','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (53,'lordgasmic','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (54,'lordgasmic','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (42,'lordgasmic','12/17/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (43,'lordgasmic','12/17/21','');
insert into wine_rating (wine_id, user, date, rating) values (44,'lordgasmic','12/17/21','');
insert into wine_rating (wine_id, user, date, rating) values (45,'lordgasmic','12/17/21','check');
insert into wine_rating (wine_id, user, date, rating) values (46,'lordgasmic','12/17/21','check');
insert into wine_rating (wine_id, user, date, rating) values (47,'lordgasmic','12/17/21','');
insert into wine_rating (wine_id, user, date, rating) values (48,'lordgasmic','12/17/21','check plus');
insert into wine_rating (wine_id, user, date, rating) values (69,'lordgasmic','8/14/211','minus');
insert into wine_rating (wine_id, user, date, rating) values (70,'lordgasmic','8/14/211','check check');
insert into wine_rating (wine_id, user, date, rating) values (71,'lordgasmic','8/14/211','check');
insert into wine_rating (wine_id, user, date, rating) values (72,'lordgasmic','8/14/211','minus');
insert into wine_rating (wine_id, user, date, rating) values (73,'lordgasmic','8/14/211','check check');
insert into wine_rating (wine_id, user, date, rating) values (75,'lordgasmic','8/14/211','check');
insert into wine_rating (wine_id, user, date, rating) values (37,'lordgasmic','9/5/21','check checck');
insert into wine_rating (wine_id, user, date, rating) values (32,'lordgasmic','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (33,'lordgasmic','9/5/21','check');
insert into wine_rating (wine_id, user, date, rating) values (34,'lordgasmic','9/5/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (35,'lordgasmic','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (26,'lordgasmic','11/6/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (39,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (28,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (29,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (30,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (25,'lordgasmic','9/4/21','check minus');
insert into wine_rating (wine_id, user, date, rating) values (22,'lordgasmic','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (23,'lordgasmic','9/4/21','check plus');
insert into wine_rating (wine_id, user, date, rating) values (24,'lordgasmic','9/4/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (5,'lordgasmic','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (6,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (7,'lordgasmic','9/4/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (8,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (21,'lordgasmic','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (1,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (2,'lordgasmic','11/6/21','check');
insert into wine_rating (wine_id, user, date, rating) values (3,'lordgasmic','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (4,'lordgasmic','11/6/21','check');
